# fly.toml app configuration file generated for hentaibot on 2024-01-24T20:04:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hentaibot"
primary_region = "waw"

[build]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 512
